# Generated by Django 2.2 on 2020-08-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case_info',
            fields=[
                ('case_no', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='文件编号')),
                ('case_content', models.TextField(max_length=2000, verbose_name='文件内容')),
                ('person_name', models.CharField(blank=True, max_length=20, verbose_name='姓名')),
                ('person_type', models.CharField(blank=True, choices=[('被告人', '被告人'), ('罪犯', '罪犯'), ('其他', '其他')], max_length=10, verbose_name='角色类型')),
                ('person_nation', models.CharField(blank=True, max_length=20, verbose_name='民族')),
                ('person_birthday', models.CharField(blank=True, max_length=20, verbose_name='出生日期')),
                ('person_age', models.CharField(blank=True, max_length=10, verbose_name='年龄')),
                ('person_sex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女'), ('未知', '未知')], max_length=10, verbose_name='性别')),
                ('person_job', models.CharField(blank=True, max_length=10, verbose_name='职业')),
                ('person_address', models.CharField(blank=True, max_length=20, verbose_name='户籍')),
                ('person_edu', models.CharField(blank=True, max_length=20, verbose_name='文化程度')),
                ('result_type', models.CharField(blank=True, max_length=10, verbose_name='判决类型')),
                ('wenshu_type', models.CharField(blank=True, max_length=10, verbose_name='文书类型')),
                ('penalty_name', models.CharField(blank=True, max_length=20, verbose_name='罪名')),
                ('penalty_content', models.CharField(blank=True, max_length=20, verbose_name='刑期')),
                ('penalty_addition_money', models.CharField(blank=True, max_length=20, verbose_name='罚金')),
                ('penalty_compensate_money', models.CharField(blank=True, max_length=20, verbose_name='民事赔偿')),
                ('penalty_addition_politics', models.CharField(blank=True, max_length=20, verbose_name='政治权利')),
                ('restricted_date', models.CharField(blank=True, max_length=20, verbose_name='取保候审时间')),
                ('arrest_date', models.CharField(blank=True, max_length=20, verbose_name='逮捕日期')),
                ('prosecutors_date', models.CharField(blank=True, max_length=20, verbose_name='公诉时间')),
                ('decision_date', models.CharField(blank=True, max_length=20, verbose_name='判决时间')),
                ('civil_plaintiff', models.CharField(blank=True, max_length=20, verbose_name='附带民事诉讼原告')),
                ('public_prosecutor', models.CharField(blank=True, max_length=20, verbose_name='公诉人')),
            ],
            options={
                'verbose_name': '文书信息',
                'verbose_name_plural': '文书信息',
                'db_table': 'wenshu_info',
            },
        ),
        migrations.CreateModel(
            name='apply_laws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_item', models.CharField(blank=True, max_length=20, verbose_name='条')),
                ('law_item_second', models.CharField(blank=True, max_length=20, verbose_name='款')),
                ('law_item_content', models.CharField(blank=True, max_length=100, verbose_name='适用情节')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law_case_no', to='wenshu.case_info')),
            ],
            options={
                'verbose_name': '法定情节',
                'verbose_name_plural': '法定情节',
                'db_table': 'wenshu_apply_laws',
            },
        ),
    ]
