# Generated by Django 2.2 on 2020-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenshu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_info',
            name='arrest_date',
            field=models.DateField(blank=True, verbose_name='逮捕日期'),
        ),
        migrations.AlterField(
            model_name='case_info',
            name='decision_date',
            field=models.DateField(blank=True, verbose_name='判决时间'),
        ),
        migrations.AlterField(
            model_name='case_info',
            name='person_birthday',
            field=models.DateField(blank=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='case_info',
            name='prosecutors_date',
            field=models.DateField(blank=True, verbose_name='公诉时间'),
        ),
        migrations.AlterField(
            model_name='case_info',
            name='restricted_date',
            field=models.DateField(blank=True, verbose_name='取保候审时间'),
        ),
    ]
