# Generated by Django 2.2 on 2020-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenshu', '0002_auto_20200815_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_info',
            name='penalty_addition_money',
            field=models.FloatField(blank=True, verbose_name='罚金'),
        ),
        migrations.AlterField(
            model_name='case_info',
            name='penalty_compensate_money',
            field=models.FloatField(blank=True, verbose_name='民事赔偿'),
        ),
        migrations.AlterField(
            model_name='case_info',
            name='person_age',
            field=models.IntegerField(blank=True, verbose_name='年龄'),
        ),
    ]
